export const SEND_REQUEST = 'POWER_RANGER_SEND_REQUEST';
export const SEND_REQUEST_FAILURE = SEND_REQUEST + '_FAILURE';
export const RECEIVE_ALL = 'POWER_RANGER_RECEIVE_ALL';
export const RECEIVE_ONE = 'POWER_RANGER_RECEIVE_ONE';
